site_name: MLOps Guide


repo_name: mlops-guide
repo_url: https://github.com/MLOPsStudyGroup/mlops-guide

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo-white.png

  features:
    - navigation.expand
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: #2c52db
      accent: orange
      toggle:
        icon: octicons/moon-16
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: #2c52db
      accent: orange
      toggle:
        icon: octicons/sun-16
        title: Switch to light mode
        name: Switch to light mode
  
  icon:
    repo: fontawesome/brands/github-alt

nav:
    - Home: 'index.md'
    - MLOps:
      - 'MLOps/Principles/index.md'
      - 'MLOps/Data/index.md'
      - 'MLOps/PipelineAutomation/index.md'
      - 'MLOps/FeatureStore/index.md'
      - 'MLOps/CICDML/index.md'
      - 'MLOps/Monitoring/index.md'
    - Guide:
      - 'Structure/index.md'
      - 'Infraestrutura/index.md'
      - 'Deployment/index.md'
      - 'CICD/index.md'
      - 'Openscale/index.md'

    - Misc.:
      - 'Testes/index.md'

