site_name: MLOps Guide
site_url: https://mlops-guide.github.io/
site_author: Arthur Olga, Gabriel Monteiro, Guilherme Leite, Vinicius Lima
site_description: >-
  MLOps Guide introducing concepts and application using DVC, CML, IBM Watson Machine Learning, IBM Watson OpenScale, Terraform and Cookiecutter. Learn how to implement MLOps.

repo_name: mlops-guide
repo_url: https://github.com/mlops-guide/mlops-guide.github.io
edit_uri: "tree/main/docs"

theme: 
  name: material
  favicon: assets/favicon.png
  logo: assets/logo-white.png

  features:
    - navigation.extend
  palette:
    # Light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: light blue
      accent: orange
      toggle:
        icon: octicons/moon-16
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: light blue
      accent: orange
      toggle:
        icon: octicons/sun-16
        name: Switch to light mode
  
  icon:
    repo: fontawesome/brands/github-alt

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - footnotes


nav:
    - Home: 'index.md'
    - Contents: 'glossary.md'
    - Principles of MLOps:
      - 'MLOps/Data/index.md'
      - 'MLOps/PipelineAutomation/index.md'
      - 'MLOps/FeatureStore/index.md'
      - 'MLOps/CICDML/index.md'
      - 'MLOps/Monitoring/index.md'
    - Implementation Guide:
      - Introduction:
        - 'Structure/project_structure.md'
        - 'Structure/starting.md'
      - Environment:
        - 'Infraestrutura/Auth/index.md'
        - 'Infraestrutura/Terraform/index.md'
        - 'Infraestrutura/Python/index.md'
      - Versioning:
        - 'Versionamento/index.md'
        - 'Versionamento/basic_dvc.md'
        - 'Versionamento/pipelines_dvc.md'
      - 'Deployment/index.md'
      - CI/CD for Machine Learning:
        - 'CICD/tests.md'
        - 'CICD/cml_testing.md'
        - 'CICD/cml_deploy.md'
      - 'Openscale/index.md'
    - Project Workflow: 'Workflow/index.md'

extra_css:
  - ASCII_cinema/asciinema-player.css
  - _css/extra_css.css
extra_javascript:
  - ASCII_cinema/asciinema-player.js
  - _js/extra_js.js
